source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.2'
# Repository for collecting Locale data for Ruby on Rails I18n as well as other interesting, Rails related I18n stuff
gem 'rails-i18n'
# Manage Procfile-based applications
gem 'foreman'
# Flexible authentication solution for Rails with Warden. 
gem 'devise'
# Translations for the devise gem 
gem 'devise-i18n'
# Rails gem of the Bootstrap based admin theme SB Admin 2
gem 'bootstrap_sb_admin_base_v2'
# Help ActiveRecord::Enum feature to work fine with I18n and simple_form.
gem 'enum_help'
# Minimal authorization through OO design and pure Ruby classes 
gem 'pundit'
# Integration of RubyMoney - Money with Rails 
gem 'money-rails'
# Easy file attachment management for ActiveRecord.
gem 'paperclip', '~> 5.0.0'
# jQuery UI for the Rails asset pipeline
gem 'jquery-ui-rails'
# The safe Markdown parser, reloaded.
gem 'redcarpet'
# FriendlyId is the “Swiss Army bulldozer” of slugging and permalink plugins for ActiveRecord.
gem 'friendly_id'
# If Turbolinks are not enough for you. Wiselinks makes your application work faster.
gem 'wiselinks'
# A Scope & Engine based, clean, powerful, customizable and sophisticated paginator for Ruby webapps 
gem 'kaminari'
# Translations for the kaminari gem
gem 'kaminari-i18n'
# A Ruby Gem that wraps the functionality of jQuery Raty library, and provides optional IMDB style rating.
gem 'ratyrate'
# Biblioteca de integração em Ruby
gem "pagseguro-oficial", "~> 2.5.0"
# Prawn Handler for Rails. Handles and registers pdf formats.
gem 'prawn-rails'
# PDF generator (from HTML) plugin for Ruby on Rails 
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
# Create beautiful JavaScript charts with one line of Ruby https://www.chartkick.com
gem 'chartkick'

# Intelligent search made easy with Rails and Elasticsearch
# gem 'searchkick'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

source 'https://rails-assets.org' do
  # Assets bootstrap
  gem 'rails-assets-bootstrap', '3.3.7'
  # Bootstrap Notify
  gem 'rails-assets-bootstrap.growl'
  # BootboxJS. Library for box confirmation and messages.
  gem 'rails-assets-bootbox'
  # Animate Css
  gem 'rails-assets-animate-css'
  # Bootstrap Markdown
  gem 'rails-assets-bootstrap-markdown'
  # Gem Marked
  gem 'rails-assets-marked'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  # RSpec for Rails-3
  gem 'rspec-rails', '~> 3.5'
  # A library for generating fake data such as names, addresses, and phone numbers. 
  gem 'faker'
end

group :test do
	 # Strategies for cleaning databases in Ruby. Can be used to ensure a clean state for testing. 
  gem 'database_cleaner'
  # Collection of testing matchers extracted from Shoulda.
  gem 'shoulda-matchers', '~> 3.1'
  # factory_girl is a fixtures replacement with a straightforward definition syntax
  gem 'factory_girl_rails'
  # A library for generating fake data such as names, addresses, and phone numbers. 
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Markdown Lorem Ipsum generator 
  gem 'doctor_ipsum'
  # Better error page for Rack apps
  gem "better_errors"
  # Generate Entity-Relationship Diagrams for Rails applications
  gem 'rails-erd'
  # Library for generating fake data.
  gem 'lerolero_generator'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # Catches mail and serves it through a dream.
  gem 'mailcatcher'
  # Classy web-development dressed in a DSL (official / canonical repo).
  #gem 'sinatra', '2.0.0.beta2'
  # Remote multi-server automation tool
  gem 'capistrano', '~> 3.7'
  # Official Ruby on Rails specific tasks for Capistrano.
  gem 'capistrano-bundler', '~> 1.2'
  # Bundler support for Capistrano 3.x
  gem 'capistrano-rails', '~> 1.2'
  # RVM support for Capistrano 3.x
  gem 'capistrano-rvm'
  # Unicorn support for Capistrano 3.
  gem 'capistrano3-unicorn'
  # Rack Middleware for handling Cross-Origin Resource Sharing (CORS), which makes cross-origin AJAX possible.
  gem 'rack-cors', :require => 'rack/cors'
end

group :production do
  # MySQL Adapter
  gem 'mysql2', '~> 0.3.18'
  # Use Capistrano for deployment
  gem 'unicorn'
end

